# This is a basic workflow to help you get started with Actions

name: build
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Install the .NET SDK indicated in the global.json file
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            7.x.x
            8.x.x
            9.x.x

      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
