# This is a basic workflow to help you get started with Actions

name: lint
on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      # Install the .NET SDK indicated in the global.json file
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            7.x.x
            8.x.x
            9.x.x
      - name: install
        run: npm ci
      - name: Lint
        run: npm run lint
